joy_linux_node:
  ros__parameters:
    deadzone: 0.05
    autorepeat_rate: 10.0
    coalesce_interval: 0.05

rapha_teleop:
  ros__parameters:
    axis_speed: 1
    scale_speed: 0.5
    axis_steer: 3
    scale_steer: 1.1
    button_deadman: 5
    button_change_steering_mode: 1
