name: CI-Foxy

on:
  workflow_dispatch:
  push:
    branches:
      - foxy
  pull_request:
    branches:
      - foxy

env:
 ROS_DISTRO: foxy

jobs:
  industrial_ci:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        ROS_REPO: [testing, main]
    env:
      ROS_REPO: ${{ matrix.ROS_REPO }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Source tests
        uses: "ros-industrial/industrial_ci@master"
        env:
          DOWNSTREAM_WORKSPACE: "github:LeoRover/leo_common-ros2 github:fictionlab/leo2_desktop#foxy github:fictionlab/leo2_robot#foxy"
          ADDITIONAL_DEBS: git-core
          AFTER_INIT: git config --global url."https://token:${{secrets.GITHUBPAT}}@github.com/".insteadOf "https://github.com/"

  ament_lint:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-20.04
    container:
      image: ubuntu:focal
    strategy:
      fail-fast: false
      matrix:
        linter: [lint_cmake, xmllint]
    steps:
      - uses: actions/checkout@v3
      - uses: ros-tooling/setup-ros@v0.3
        with:
          required-ros-distributions: ${{ env.ROS_DISTRO }}
      - uses: ros-tooling/action-ros-lint@v0.1
        with:
          distribution: ${{ env.ROS_DISTRO }}
          linter: ${{ matrix.linter }}
          package-name: |
            leo2
            leo2_description
            leo2_teleop
